package com.yasser.ub.real
import android.app.DatePickerDialog
import android.app.TimePickerDialog
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
import retrofit2.HttpException
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.Calendar
private val Blue=Color(0xFF0B5CFF)
private enum class S{LOGIN,REGISTER,HOME,RESOURCES,BOOK,BOOKINGS,REPORTS,PROFILE}
@Composable fun CpebRealApp(){
 val ctx=LocalContext.current;val ses=remember{Session(ctx)};val co=rememberCoroutineScope()
 var s by remember{mutableStateOf(if(ses.token==null)S.LOGIN else S.HOME)};var err by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)}
 var rs by remember{mutableStateOf<List<EquipmentDto>>(emptyList())};var bs by remember{mutableStateOf<List<BookingDto>>(emptyList())};var ps by remember{mutableStateOf<List<ReportDto>>(emptyList())};var sel by remember{mutableStateOf<EquipmentDto?>(null)}
 fun msg(t:Throwable)=if(t is HttpException)t.response()?.errorBody()?.string()?:"Request failed" else t.message?:"Cannot connect";fun a()=ses.bearer()
 fun load(){co.launch{busy=true;err="";try{rs=ApiFactory.api.equipment(a());bs=ApiFactory.api.bookings(a());ps=ApiFactory.api.reports(a())}catch(t:Throwable){err=msg(t)};busy=false}}
 LaunchedEffect(ses.token){if(ses.token!=null)load()}
 MaterialTheme(colorScheme=lightColorScheme(primary=Blue)){Scaffold(bottomBar={if(s!=S.LOGIN&&s!=S.REGISTER)NavigationBar{listOf(S.HOME to"Home",S.RESOURCES to"Resources",S.BOOKINGS to"Bookings",S.REPORTS to"Reports",S.PROFILE to"Profile").forEach{(x,n)->NavigationBarItem(s==x,{s=x},{Text(n.take(1))},{Text(n)})}}}){p->Box(Modifier.padding(p).fillMaxSize()){when(s){
 S.LOGIN->Login(busy,err,{e,pw->co.launch{busy=true;err="";try{val r=ApiFactory.api.login(LoginBody(e,pw));ses.token=r.accessToken;ses.name=r.user.fullName;s=S.HOME}catch(t:Throwable){err=msg(t)};busy=false}},{s=S.REGISTER})
 S.REGISTER->Register(busy,err,{s=S.LOGIN},{n,e,pw->co.launch{busy=true;err="";try{val r=ApiFactory.api.register(RegisterBody(n,e,pw));ses.token=r.accessToken;ses.name=r.user.fullName;s=S.HOME}catch(t:Throwable){err=msg(t)};busy=false}})
 S.HOME->Frame("Hello, ${ses.name?:"Student"}"){Text("Real database");Text("Resources ${rs.size} • Bookings ${bs.size} • Reports ${ps.size}");Button({s=S.RESOURCES},Modifier.fillMaxWidth()){Text("Browse resources")};OutlinedButton({load()},Modifier.fillMaxWidth()){Text(if(busy)"Loading..." else"Refresh")};if(err.isNotBlank())Text(err,color=Color.Red)}
 S.RESOURCES->Resources(rs){sel=it;s=S.BOOK}
 S.BOOK->sel?.let{x->Book(x,err,busy,{s=S.RESOURCES}){st,en,re->co.launch{busy=true;err="";try{val v=ApiFactory.api.availability(a(),x.id,st,en);if(!v.available)err=v.reason else{ApiFactory.api.book(a(),BookingBody(x.id,st,en,re));bs=ApiFactory.api.bookings(a());s=S.BOOKINGS}}catch(t:Throwable){err=msg(t)};busy=false}}}
 S.BOOKINGS->Bookings(bs,err,{load()},{id->co.launch{try{ApiFactory.api.cancel(a(),id);bs=ApiFactory.api.bookings(a())}catch(t:Throwable){err=msg(t)}}},{id->co.launch{try{ApiFactory.api.finish(a(),id);bs=ApiFactory.api.bookings(a())}catch(t:Throwable){err=msg(t)}}})
 S.REPORTS->Reports(ps,rs,err,{load()}){id,t,d->co.launch{try{ApiFactory.api.report(a(),ReportBody(id,t,d));ps=ApiFactory.api.reports(a())}catch(x:Throwable){err=msg(x)}}}
 S.PROFILE->Frame("Profile"){Text(ses.name?:"Student",fontWeight=FontWeight.Bold);Text(ApiFactory.BASE_URL);Button({ses.clear();rs=emptyList();bs=emptyList();ps=emptyList();s=S.LOGIN},colors=ButtonDefaults.buttonColors(containerColor=Color.Red),modifier=Modifier.fillMaxWidth()){Text("Log out")}}
 }}}}
}
@Composable private fun Frame(t:String,c:@Composable ColumnScope.()->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Text(t,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black)};item{Column(verticalArrangement=Arrangement.spacedBy(12.dp),content=c)}}}
@Composable private fun Login(b:Boolean,e:String,go:(String,String)->Unit,reg:()->Unit){var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};Frame("University Sign In"){OutlinedTextField(u,{u=it},label={Text("University email")},modifier=Modifier.fillMaxWidth());OutlinedTextField(p,{p=it},label={Text("Password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());if(e.isNotBlank())Text(e,color=Color.Red);Button({go(u,p)},enabled=!b&&u.contains("@")&&p.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text(if(b)"Signing in..." else"Sign in")};TextButton(reg,Modifier.align(Alignment.CenterHorizontally)){Text("Create student account")};Text("Fake verification removed: registration is real and immediate.")}}
@Composable private fun Register(b:Boolean,e:String,back:()->Unit,go:(String,String,String)->Unit){var n by remember{mutableStateOf("")};var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};Frame("Create Account"){OutlinedTextField(n,{n=it},label={Text("Full name")},modifier=Modifier.fillMaxWidth());OutlinedTextField(u,{u=it},label={Text("Email")},modifier=Modifier.fillMaxWidth());OutlinedTextField(p,{p=it},label={Text("Password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());if(e.isNotBlank())Text(e,color=Color.Red);Button({go(n,u,p)},enabled=!b&&n.isNotBlank()&&u.contains("@")&&p.length>=6,modifier=Modifier.fillMaxWidth()){Text("Create account")};TextButton(back){Text("Back")}}}
@Composable private fun Resources(r:List<EquipmentDto>,pick:(EquipmentDto)->Unit){var c by remember{mutableStateOf("ALL")};val cs=listOf("ALL")+r.map{it.category}.distinct();LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Resources",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black)};item{Column{cs.forEach{x->FilterChip(c==x,{c=x},{Text(x)})}}};items(r.filter{c=="ALL"||it.category==c}){x->Card(Modifier.fillMaxWidth().clickable{pick(x)},shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp)){Text(x.name,fontWeight=FontWeight.Black);Text("${x.category} • ${x.inventoryTag}");Text(x.location?:"Campus");Text(x.status);x.description?.let{Text(it)}}}}}}
@Composable private fun Book(x:EquipmentDto,e:String,b:Boolean,back:()->Unit,go:(String,String,String)->Unit){val ctx=LocalContext.current;var d by remember{mutableStateOf("")};var st by remember{mutableStateOf("")};var en by remember{mutableStateOf("")};var r by remember{mutableStateOf("")};fun pd(){val c=Calendar.getInstance();DatePickerDialog(ctx,{_,y,m,z->d="%04d-%02d-%02d".format(y,m+1,z)},c[1],c[2],c[5]).show()};fun pt(set:(String)->Unit){val c=Calendar.getInstance();TimePickerDialog(ctx,{_,h,m->set("%02d:%02d".format(h,m))},c[11],c[12],true).show()};Frame("Book ${x.name}"){Text("Any day, including Saturday and Sunday.");OutlinedButton({pd()},Modifier.fillMaxWidth()){Text(if(d=="")"Choose date" else d)};Row{OutlinedButton({pt{st=it}},Modifier.weight(1f)){Text(if(st=="")"Start" else st)};OutlinedButton({pt{en=it}},Modifier.weight(1f)){Text(if(en=="")"End" else en)}};OutlinedTextField(r,{r=it},label={Text("Purpose")},modifier=Modifier.fillMaxWidth());if(e.isNotBlank())Text(e,color=Color.Red);Button({val f=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");go(LocalDateTime.parse("$d $st",f).atZone(ZoneId.systemDefault()).toInstant().toString(),LocalDateTime.parse("$d $en",f).atZone(ZoneId.systemDefault()).toInstant().toString(),r)},enabled=!b&&d!=""&&st!=""&&en!="",modifier=Modifier.fillMaxWidth()){Text("Check and book")};TextButton(back){Text("Back")}}}
@Composable private fun Bookings(v:List<BookingDto>,e:String,ref:()->Unit,cancel:(String)->Unit,finish:(String)->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("My Bookings",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black)};item{OutlinedButton(ref){Text("Refresh")};if(e.isNotBlank())Text(e,color=Color.Red)};items(v){x->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.equipment.name,fontWeight=FontWeight.Black);Text("${x.startTime} → ${x.endTime}");Text(x.status);Row{if(x.status=="APPROVED"||x.status=="PENDING")OutlinedButton({cancel(x.id)}){Text("Cancel")};if(x.status!="CLOSED"&&x.status!="CANCELLED"&&x.status!="REJECTED")Button({finish(x.id)}){Text("Finish")}}}}}}}
@Composable private fun Reports(v:List<ReportDto>,r:List<EquipmentDto>,e:String,ref:()->Unit,go:(String,String,String)->Unit){var q by remember{mutableStateOf(r.firstOrNull())};var t by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("My Reports",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black)};item{Column{Text("Resource: ${q?.name?:"None"}");r.take(6).forEach{x->AssistChip({q=x},{Text(x.name.take(18))})};OutlinedTextField(t,{t=it},label={Text("Title")},modifier=Modifier.fillMaxWidth());OutlinedTextField(d,{d=it},label={Text("Description")},modifier=Modifier.fillMaxWidth());Button({q?.let{go(it.id,t,d);t="";d=""}},enabled=q!=null&&t!="",modifier=Modifier.fillMaxWidth()){Text("Send to database")};OutlinedButton(ref){Text("Refresh")};if(e.isNotBlank())Text(e,color=Color.Red)}};items(v){x->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.title,fontWeight=FontWeight.Black);Text(x.equipment.name);Text(x.status);x.description?.let{Text(it)}}}}}}