import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { BookingStatus,EquipmentStatus,MaintenanceStatus,RepairTicketStatus,UserRole } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable()
export class AdminService {
 constructor(private readonly p:PrismaService){}
 async dashboard(){const [u,ua,e,ea,bp,ba,r,m]=await this.p.$transaction([this.p.user.count(),this.p.user.count({where:{isActive:true}}),this.p.equipment.count(),this.p.equipment.count({where:{status:EquipmentStatus.AVAILABLE}}),this.p.booking.count({where:{status:BookingStatus.PENDING}}),this.p.booking.count({where:{status:{in:[BookingStatus.APPROVED,BookingStatus.CHECKED_OUT]}}}),this.p.repairTicket.count({where:{status:{in:[RepairTicketStatus.OPEN,RepairTicketStatus.DIAGNOSING,RepairTicketStatus.WAITING_PARTS,RepairTicketStatus.READY_FOR_TEST]}}}),this.p.maintenanceRecord.count({where:{status:{in:[MaintenanceStatus.SCHEDULED,MaintenanceStatus.ACTIVE]}}})]);return{generatedAt:new Date().toISOString(),users:{total:u,active:ua},equipment:{total:e,available:ea},bookings:{pending:bp,active:ba},reports:{open:r},maintenance:{active:m}}}
 users(role?:UserRole,active?:boolean){return this.p.user.findMany({where:{role,isActive:active},select:{id:true,fullName:true,email:true,role:true,isActive:true,createdAt:true,updatedAt:true},orderBy:[{role:'asc'},{fullName:'asc'}]})}
 async updateUser(actorId:string,userId:string,b:{role?:UserRole;isActive?:boolean}){const old=await this.p.user.findUnique({where:{id:userId}});if(!old)throw new NotFoundException('User not found');if(actorId===userId&&b.isActive===false)throw new BadRequestException('Cannot deactivate own account');const x=await this.p.user.update({where:{id:userId},data:b,select:{id:true,fullName:true,email:true,role:true,isActive:true,updatedAt:true}});await this.log(actorId,'USER_UPDATED','USER',userId,undefined,undefined,{previousRole:old.role,newRole:x.role,previousActive:old.isActive,newActive:x.isActive});return x}
 bookings(status?:BookingStatus){return this.p.booking.findMany({where:{status},include:{equipment:true,user:{select:{id:true,fullName:true,email:true,role:true}}},orderBy:[{startTime:'asc'},{createdAt:'desc'}]})}
 async bookingStatus(actorId:string,id:string,status:BookingStatus,action:string,metadata?:Record<string,unknown>){const old=await this.p.booking.findUnique({where:{id}});if(!old)throw new NotFoundException('Booking not found');if(old.status===BookingStatus.CANCELLED||old.status===BookingStatus.REJECTED||old.status===BookingStatus.CLOSED)throw new BadRequestException(`Booking already ${old.status}`);const x=await this.p.booking.update({where:{id},data:{status},include:{equipment:true,user:{select:{id:true,fullName:true,email:true}}}});await this.log(actorId,action,'BOOKING',id,old.equipmentId,id,{previousStatus:old.status,newStatus:x.status,...(metadata??{})});return x}
 equipment(category?:string,status?:EquipmentStatus){return this.p.equipment.findMany({where:{category:category?{equals:category,mode:'insensitive'}:undefined,status},orderBy:[{category:'asc'},{name:'asc'},{inventoryTag:'asc'}]})}
 async createEquipment(actorId:string,b:any){if(!b.name?.trim()||!b.category?.trim()||!b.inventoryTag?.trim())throw new BadRequestException('Name, category and inventory tag required');if(await this.p.equipment.findUnique({where:{inventoryTag:b.inventoryTag.trim().toUpperCase()}}))throw new ConflictException('Inventory tag already used');const x=await this.p.equipment.create({data:{name:b.name.trim(),category:b.category.trim().toUpperCase(),inventoryTag:b.inventoryTag.trim().toUpperCase(),location:b.location?.trim(),description:b.description?.trim(),status:EquipmentStatus.AVAILABLE}});await this.log(actorId,'EQUIPMENT_CREATED','EQUIPMENT',x.id,x.id);return x}
 async equipmentStatus(actorId:string,id:string,status:EquipmentStatus){const old=await this.p.equipment.findUnique({where:{id}});if(!old)throw new NotFoundException('Equipment not found');const x=await this.p.equipment.update({where:{id},data:{status}});await this.log(actorId,'EQUIPMENT_STATUS_UPDATED','EQUIPMENT',id,id,undefined,{previousStatus:old.status,newStatus:x.status});return x}
 reports(status?:RepairTicketStatus){return this.p.repairTicket.findMany({where:{status},include:{equipment:true,technician:{select:{id:true,fullName:true,email:true}},reporter:{select:{id:true,fullName:true,email:true}}},orderBy:{createdAt:'desc'}})}
 async reportStatus(actorId:string,id:string,status:RepairTicketStatus,diagnosis?:string){const old=await this.p.repairTicket.findUnique({where:{id}});if(!old)throw new NotFoundException('Report not found');const x=await this.p.repairTicket.update({where:{id},data:{status,diagnosis:diagnosis===undefined?undefined:diagnosis.trim()},include:{equipment:true,technician:true,reporter:true}});await this.log(actorId,'REPORT_STATUS_UPDATED','REPAIR_TICKET',id,old.equipmentId,undefined,{previousStatus:old.status,newStatus:x.status});return x}
 async assignReport(actorId:string,id:string,technicianId:string){const [r,t]=await Promise.all([this.p.repairTicket.findUnique({where:{id}}),this.p.user.findUnique({where:{id:technicianId}})]);if(!r)throw new NotFoundException('Report not found');if(!t||t.role!==UserRole.TECHNICIAN||!t.isActive)throw new BadRequestException('Active technician required');const x=await this.p.repairTicket.update({where:{id},data:{technicianId,status:r.status===RepairTicketStatus.OPEN?RepairTicketStatus.DIAGNOSING:r.status},include:{equipment:true,technician:true,reporter:true}});await this.log(actorId,'REPORT_ASSIGNED','REPAIR_TICKET',id,r.equipmentId,undefined,{technicianId});return x}
 maintenance(status?:MaintenanceStatus){return this.p.maintenanceRecord.findMany({where:{status},include:{equipment:true},orderBy:[{startTime:'asc'},{createdAt:'desc'}]})}
 async createMaintenance(actorId:string,b:any){const a=new Date(b.startTime),z=new Date(b.endTime);if(Number.isNaN(a.getTime())||Number.isNaN(z.getTime())||a>=z)throw new BadRequestException('Valid times required');if(!await this.p.equipment.findUnique({where:{id:b.equipmentId}}))throw new NotFoundException('Equipment not found');const c=await this.p.booking.findFirst({where:{equipmentId:b.equipmentId,status:{in:[BookingStatus.PENDING,BookingStatus.APPROVED,BookingStatus.CHECKED_OUT]},startTime:{lt:z},endTime:{gt:a}}});if(c)throw new ConflictException('Maintenance conflicts with booking');const x=await this.p.maintenanceRecord.create({data:{equipmentId:b.equipmentId,title:b.title.trim(),description:b.description?.trim(),startTime:a,endTime:z,status:MaintenanceStatus.SCHEDULED},include:{equipment:true}});await this.log(actorId,'MAINTENANCE_CREATED','MAINTENANCE',x.id,b.equipmentId);return x}
 async maintenanceStatus(actorId:string,id:string,status:MaintenanceStatus){const old=await this.p.maintenanceRecord.findUnique({where:{id}});if(!old)throw new NotFoundException('Maintenance not found');const x=await this.p.maintenanceRecord.update({where:{id},data:{status},include:{equipment:true}});if(status===MaintenanceStatus.ACTIVE)await this.p.equipment.update({where:{id:old.equipmentId},data:{status:EquipmentStatus.UNDER_MAINTENANCE}});if(status===MaintenanceStatus.COMPLETED||status===MaintenanceStatus.CANCELLED)await this.p.equipment.update({where:{id:old.equipmentId},data:{status:EquipmentStatus.AVAILABLE}});await this.log(actorId,'MAINTENANCE_STATUS_UPDATED','MAINTENANCE',id,old.equipmentId,undefined,{previousStatus:old.status,newStatus:x.status});return x}
 audit(take:number){const n=Number.isFinite(take)?Math.min(Math.max(Math.trunc(take),1),500):100;return this.p.auditLog.findMany({take:n,include:{actor:{select:{id:true,fullName:true,email:true,role:true}},equipment:true,booking:true},orderBy:{createdAt:'desc'}})}
 private log(actorId:string|undefined,action:string,entityType:string,entityId?:string,equipmentId?:string,bookingId?:string,metadata?:Record<string,unknown>){return this.p.auditLog.create({data:{actorId,action,entityType,entityId,equipmentId,bookingId,metadata: metadata as any}})}
}
