import {BadRequestException,ConflictException,Injectable,NotFoundException} from '@nestjs/common';
import {BookingStatus,EquipmentStatus,MaintenanceStatus} from '@prisma/client';
import {PrismaService} from '../prisma/prisma.service';
type Win={equipmentId:string,startTime:string,endTime:string};type Create=Win&{userId:string,reason?:string};
@Injectable() export class BookingsService{
 constructor(private readonly p:PrismaService){}
 private dates(s:string,e:string){const a=new Date(s),b=new Date(e);if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))throw new BadRequestException('Invalid date');if(a>=b)throw new BadRequestException('Start must be before end');if(a<new Date())throw new BadRequestException('Time must be in future');return{a,b}}
 async availability(i:Win){const{a,b}=this.dates(i.startTime,i.endTime);const eq=await this.p.equipment.findUnique({where:{id:i.equipmentId}});if(!eq)throw new NotFoundException('Resource not found');if([EquipmentStatus.UNDER_MAINTENANCE,EquipmentStatus.LOST,EquipmentStatus.RETIRED].includes(eq.status))return{available:false,reason:`Resource status is ${eq.status}`};const m=await this.p.maintenanceRecord.findFirst({where:{equipmentId:i.equipmentId,status:{in:[MaintenanceStatus.SCHEDULED,MaintenanceStatus.ACTIVE]},startTime:{lt:b},endTime:{gt:a}}});if(m)return{available:false,reason:'Maintenance conflict'};const c=await this.p.booking.findFirst({where:{equipmentId:i.equipmentId,status:{in:[BookingStatus.PENDING,BookingStatus.APPROVED,BookingStatus.CHECKED_OUT]},startTime:{lt:b},endTime:{gt:a}}});return c?{available:false,reason:'Already booked'}:{available:true,reason:'Available'}}
 async create(i:Create){const av=await this.availability(i);if(!av.available)throw new ConflictException(av.reason);const{a,b}=this.dates(i.startTime,i.endTime);return this.p.booking.create({data:{equipmentId:i.equipmentId,userId:i.userId,startTime:a,endTime:b,reason:i.reason,status:BookingStatus.APPROVED},include:{equipment:true}})}
 mine(userId:string){return this.p.booking.findMany({where:{userId},include:{equipment:true},orderBy:{createdAt:'desc'}})}
 async cancel(id:string,userId:string){const x=await this.p.booking.findFirst({where:{id,userId}});if(!x)throw new NotFoundException('Booking not found');if(![BookingStatus.PENDING,BookingStatus.APPROVED].includes(x.status))throw new BadRequestException('Cannot cancel');return this.p.booking.update({where:{id},data:{status:BookingStatus.CANCELLED},include:{equipment:true}})}
 async finish(id:string,userId:string){const x=await this.p.booking.findFirst({where:{id,userId}});if(!x)throw new NotFoundException('Booking not found');if([BookingStatus.CANCELLED,BookingStatus.REJECTED,BookingStatus.CLOSED].includes(x.status))throw new BadRequestException('Cannot finish');return this.p.booking.update({where:{id},data:{status:BookingStatus.CLOSED},include:{equipment:true}})}
}